### ISSUE TITLE
How to add a host 

### ISSUE THREAD

**Issue by davidgatti** [zoom/api#10]
I still can't understand how to add a host to a meeting. For example when I want to record the video I get the following message: `Please request record permission from the meeting host`. This is the request that I make to this endpoint `/v2/users/' + process.env.ZOOM_USER_ID + '/meetings`:

```javascript
{
	topic: "1 on 1 Call",
	agenda: "1 on 1 Call",
	recurrence: {
		type: 2
	},
	settings: {
		join_before_host: true,
		auto_recording: 'cloud'
	}
}
```

This way anyone can join and have a meeting. I did find an option in the zoom UI where I can claim to be the host if I punch a PIN. But in the endpoint I see no such option to provide a PIN.

What am I not getting? And as far as I can see I can't find any info in the documentation that explain how this meeting relation works.

**Comment by joshuawoodward** [comment]
@davidgatti 
I tested this and got the expected behavior.

I created a test meeting using one user id and the same settings (I didn't do a recurring meeting)

Then as another user I joined the meeting. I was entered into the meeting before the host joined, (the host never joined) and as I entered the recording indicator was on. After the meeting ended the recording appeared in the host's "My Recordings" section (and was available via API as well)
